### ISSUE TITLE
css_merger: theme-specific styles break on windows (was: Something's still broken on Windows)

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/grunt-laxar#37]
After fixing #35 and #36 I'm still having issues when "optimizing" my application on Windows.

It looks like the widget specific styles are missing, so I suspect there's something wrong with the `directory_tree` task providing the embedded CSS, but I could be wrong.

Note: The `debug.html` works fine

**Comment by x1B** [comment]
If the problem exists only with optimized apps, it's probably something with the `css_merger` task. The `directory_tree` is only used for CSS if the `debug.html` is used.

**Comment by jpommerening** [comment]
I was of the impression that `file_resource_provider.useEmbedded` includes CSS…?
The contents of my `var/listings/includes_resources.json` file (generated on OS X) seem to confirm that.

**Comment by x1B** [comment]
In this case we may need to adjust the `embedContents` configuration for the `directory_tree` settings of the application (and template) Gruntfile .

If embedded resources are used, CSS files should still only be listed, not embedded, because the application will use the CSS from the single, merged CSS file, not from any listings. Even in debug mode (where embedded resources are not used), CSS is loaded through dynamically generated `link` elements.

**Comment by jonaswjs** [comment]
Fixed on `master` (`v1.0.0`).
